In [1]:
import numpy as np

In [2]:
arr = np.array([[2,3,4],[5,6,7],[10,20,30]])
print(arr)

[[ 2  3  4]
 [ 5  6  7]
 [10 20 30]]


In [3]:
arr[2,1]

20

In [ ]:
1(col)  2(colindex)
6       7 >>> row index >1  
20      30 >> row index > 2

In [4]:
arr[1:3,1:3] # arr[1:,1:]

array([[ 6,  7],
       [20, 30]])

In [5]:
arr[1:,1:]

array([[ 6,  7],
       [20, 30]])

## 3-D

In [6]:
arr3 = np.array([[[2,3,4],[5,6,7],[10,20,30]],[[12,13,14],[23,24,25],[123,122,225]]])
print("Array\n",arr3)

Array
 [[[  2   3   4]
  [  5   6   7]
  [ 10  20  30]]

 [[ 12  13  14]
  [ 23  24  25]
  [123 122 225]]]


In [ ]:
(k,i,j)
3-D > [k(plane index),i(row index),j(col index)]

In [7]:
arr3[:,:,:]

array([[[  2,   3,   4],
        [  5,   6,   7],
        [ 10,  20,  30]],

       [[ 12,  13,  14],
        [ 23,  24,  25],
        [123, 122, 225]]])

In [ ]:
  # 6 7
#  20 30
#  24  25
# 122  225

In [8]:
arr3[:,1:,1:] 

array([[[  6,   7],
        [ 20,  30]],

       [[ 24,  25],
        [122, 225]]])

In [9]:
arr3[:,1:3,1:3] 

array([[[  6,   7],
        [ 20,  30]],

       [[ 24,  25],
        [122, 225]]])

In [10]:
arr3

array([[[  2,   3,   4],
        [  5,   6,   7],
        [ 10,  20,  30]],

       [[ 12,  13,  14],
        [ 23,  24,  25],
        [123, 122, 225]]])

In [11]:
arr3[0,1:,1:]

array([[ 6,  7],
       [20, 30]])

In [12]:
arr3[1,1:,1:]

array([[ 24,  25],
       [122, 225]])

In [13]:
arr3

array([[[  2,   3,   4],
        [  5,   6,   7],
        [ 10,  20,  30]],

       [[ 12,  13,  14],
        [ 23,  24,  25],
        [123, 122, 225]]])

In [14]:
arr3[0,2,0:2]

array([10, 20])

In [15]:
arr3[1,1,0]

23

In [16]:
arr3[1,2,2]

225

In [17]:
arr3

array([[[  2,   3,   4],
        [  5,   6,   7],
        [ 10,  20,  30]],

       [[ 12,  13,  14],
        [ 23,  24,  25],
        [123, 122, 225]]])

In [18]:
arr3[0,:,1]

array([ 3,  6, 20])

In [19]:
arr3

array([[[  2,   3,   4],
        [  5,   6,   7],
        [ 10,  20,  30]],

       [[ 12,  13,  14],
        [ 23,  24,  25],
        [123, 122, 225]]])

In [20]:
arr3[0,1:,2]

array([ 7, 30])

## Convert to n-D Array

In [21]:
arr = np.array([100,200,300,400])
print("Array\n",arr)
print()
print("Dimension of array\n",arr.ndim)

Array
 [100 200 300 400]

Dimension of array
 1


In [22]:
arr = np.array([100,200,300,400],ndmin=2)
print("Array\n",arr)
print()
print("Dimension of array\n",arr.ndim)

Array
 [[100 200 300 400]]

Dimension of array
 2


In [23]:
arr = np.array([100,200,300,400],ndmin=3)
print("Array\n",arr)
print()
print("Dimension of array\n",arr.ndim)

Array
 [[[100 200 300 400]]]

Dimension of array
 3


In [24]:
arr = np.array([[[100,200,300,400]]],ndmin=1)
print("Array\n",arr)
print()
print("Dimension of array\n",arr.ndim) # numpy can't convert higher dimension to lower dimension

Array
 [[[100 200 300 400]]]

Dimension of array
 3


## Numpy Function

## 1) reshape

In [ ]:
reshape(row_count,column_count)
uses>
used to convert 1D to 2D,3D,4D and vice versa

In [25]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
def get_display_array(array):
    print(f"Dimension={array.ndim}")
    print(f"Shape={array.shape}")
    print(f"Array\n",array)
get_display_array(arr)

Dimension=1
Shape=(12,)
Array
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
12

4,3
3,4
1,12
12,1
2,6
6,2
1,3,4
1,4,3
1,2,6
1,6,2
2,3,2

In [29]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_array = arr.reshape(2,6)
get_display_array(new_array) # calling fun
print("*"*30)
get_display_array(arr)

Dimension=2
Shape=(2, 6)
Array
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
******************************
Dimension=1
Shape=(12,)
Array
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [30]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_array = arr.reshape(1,2,6)
get_display_array(new_array) # calling fun
print("*"*30)
get_display_array(arr)

Dimension=3
Shape=(1, 2, 6)
Array
 [[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]]
******************************
Dimension=1
Shape=(12,)
Array
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [31]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_array = arr.reshape(4,3)
get_display_array(new_array) # calling fun
print("*"*30)
get_display_array(arr)

Dimension=2
Shape=(4, 3)
Array
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
******************************
Dimension=1
Shape=(12,)
Array
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [32]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_array = arr.reshape(4,8)
get_display_array(new_array) # calling fun
print("*"*30)
get_display_array(arr)

ValueError: cannot reshape array of size 12 into shape (4,8)

In [34]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,120])
new_array = arr.reshape(12,1)
get_display_array(new_array) # calling fun
print("*"*30)
get_display_array(arr)

Dimension=2
Shape=(12, 1)
Array
 [[  1]
 [  2]
 [  3]
 [  4]
 [  5]
 [  6]
 [  7]
 [  8]
 [  9]
 [ 10]
 [ 11]
 [120]]
******************************
Dimension=1
Shape=(12,)
Array
 [  1   2   3   4   5   6   7   8   9  10  11 120]


## Convert to list

In [35]:
import numpy as np

In [37]:
array = np.array([1,2,3,34,45,56])
get_display_array(array)
type(array)

Dimension=1
Shape=(6,)
Array
 [ 1  2  3 34 45 56]


numpy.ndarray

In [38]:
lst = array.tolist()
print(type(lst))

<class 'list'>


In [39]:
lst

[1, 2, 3, 34, 45, 56]

In [40]:
arr = np.array([[6,2],[2,5]])
lst =arr.tolist()
lst

[[6, 2], [2, 5]]

## Access array elements using loops

In [41]:
arr1 = np.array([1,2,3,4])
for i in arr1:
    print(i)

1
2
3
4


In [43]:
arr1 = [[2,3],[4,5]]
for i in arr1:
    for j in i:
        print(j)

2
3
4
5


In [45]:
arr1 = [[[2,3],[4,5]]]
for i in arr1:
    for j in i:
        for k in j:
            print(k)

2
3
4
5


In [51]:
arr1 = [[[[2,3],[4,5]]]]
for i in arr1:
    for j in i:
        for k in j:
            for m in k:
                print(m)

2
3
4
5


## np.nditer()

In [48]:
arr1 = [[2,3],[4,5]]
iter_obj = np.nditer(arr1)
print(iter_obj)
print(next(iter_obj))


(array(2), array(4))


In [50]:
arr1 = np.array([[2,3],[4,5]])
for i in np.nditer(arr1):
    print(i)

2
3
4
5


In [52]:
arr1 = np.array([[[[2,3],[4,5]]]])
for i in np.nditer(arr1):
    print(i)

2
3
4
5


In [53]:
arr1 = np.array([[[2,3],[4,5]],[[5,7],[6,7]]])
for i in np.nditer(arr1):
    print(i)

2
3
4
5
5
7
6
7


## 3.np.ndenumerate()

In [54]:
arr1 =np.array([1,23,4,5,6])
for i,val in np.ndenumerate(arr1):
    print("Index",i,">>>>>>","Value",val)

Index (0,) >>>>>> Value 1
Index (1,) >>>>>> Value 23
Index (2,) >>>>>> Value 4
Index (3,) >>>>>> Value 5
Index (4,) >>>>>> Value 6


In [59]:
arr1 =np.array([[[2,3],[4,5]],[[5,7],[6,7]]])
print(arr1.shape)
print(arr1)
for i,val in np.ndenumerate(arr1):
    print("Index",i,">>>>>>","Value",val)

(2, 2, 2)
[[[2 3]
  [4 5]]

 [[5 7]
  [6 7]]]
Index (0, 0, 0) >>>>>> Value 2
Index (0, 0, 1) >>>>>> Value 3
Index (0, 1, 0) >>>>>> Value 4
Index (0, 1, 1) >>>>>> Value 5
Index (1, 0, 0) >>>>>> Value 5
Index (1, 0, 1) >>>>>> Value 7
Index (1, 1, 0) >>>>>> Value 6
Index (1, 1, 1) >>>>>> Value 7


## 4.zeros()

In [ ]:
np.zeros(shape,dtyep=float)
return an array of zeros
To create refernce column /Target column
Application>
1. Target column creation or o/p col
2.Weight Initialization

In [60]:
arr = np.zeros(20)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [61]:
arr = np.zeros(20,int)
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [63]:
arr = np.zeros(100,dtype=int)
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [64]:
arr = np.zeros((2,5),dtype=int)
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [65]:
arr = np.zeros((5,2),dtype=int)
arr

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [66]:
arr = np.zeros((3,5,2),dtype=int)
arr

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])

## 5.np.ones()

In [ ]:
np.ones(shape,dtyep=float)
return an array of ones
To create refernce column /Target column
Application>
1. Target column creation or o/p col
2.Weight Initialization

In [67]:
arr = np.ones(20)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [68]:
arr = np.ones(20,int)
arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [69]:
import pandas as pd
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [71]:
df["A"] =np.zeros(10,int)
df["B"] = np.ones(10,int)
df

A  B
0  0  1
1  0  1
2  0  1
3  0  1
4  0  1
5  0  1
6  0  1
7  0  1
8  0  1
9  0  1

In [72]:
arr0 = np.zeros(500)
arr1= np.ones(500)
get_display_array(arr0) # calling fun
get_display_array(arr1)

Dimension=1
Shape=(500,)
Array
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 

In [ ]:
0
0

1
1
1
1

In [77]:
target = np.append(arr0,arr1)
df= pd.DataFrame(target)
df[499:]

0
499  0.0
500  1.0
501  1.0
502  1.0
503  1.0
..   ...
995  1.0
996  1.0
997  1.0
998  1.0
999  1.0

[501 rows x 1 columns]

## 6.arange()

In [78]:
list(range(1,20))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [ ]:
works same like range fun that we had use in python

In [79]:
arr = np.arange(2,6) # last element excluded
arr

array([2, 3, 4, 5])

In [80]:
arr = np.arange(1,10,2) # last element excluded
arr

array([1, 3, 5, 7, 9])

In [81]:
arr = np.arange(10,0,-1) # last element excluded
arr

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [82]:
arr = np.arange(-4,5) # last element excluded
arr

array([-4, -3, -2, -1,  0,  1,  2,  3,  4])

## 7.linspace()

In [ ]:
np.linspace(start,end,num=50,restep=False) # restep return step value
it return an array with evenly spaced value

In [84]:
arr = np.linspace(1,50,num=50,retstep=True)
arr

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
        40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.]),
 1.0)

In [85]:
arr = np.linspace(1,50,retstep=True)
arr

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
        40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.]),
 1.0)

In [3]:
import  numpy as np
arr = np.linspace(1,50,num=10,retstep=True)
arr[0]

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [5]:
import  numpy as np
arr = np.linspace(10,100,num=25,retstep=True)
arr

(array([ 10.  ,  13.75,  17.5 ,  21.25,  25.  ,  28.75,  32.5 ,  36.25,
         40.  ,  43.75,  47.5 ,  51.25,  55.  ,  58.75,  62.5 ,  66.25,
         70.  ,  73.75,  77.5 ,  81.25,  85.  ,  88.75,  92.5 ,  96.25,
        100.  ]),
 3.75)

In [20]:
arr1=np.random.randint(10,20,size=16).reshape(4,4)

print(arr1)
arr2=np.max(arr1)
print("maximun is>>>>>",arr2)

[[14 19 17 11]
 [16 16 16 13]
 [18 10 18 15]
 [11 15 18 16]]
maximun is>>>>> 19


In [87]:
49/9

5.444444444444445

In [96]:
arr = np.linspace(1,50,num=4,retstep=True)
arr

(array([ 1.        , 17.33333333, 33.66666667, 50.        ]),
 16.333333333333332)

In [95]:
49/3

16.333333333333332

In [98]:
arr = np.linspace(2,10,num=10)
arr

array([ 2.        ,  2.88888889,  3.77777778,  4.66666667,  5.55555556,
        6.44444444,  7.33333333,  8.22222222,  9.11111111, 10.        ])

In [100]:
8/9

0.8888888888888888

In [144]:
ar = np.random.rand(12)
ar

array([0.25462538, 0.46689897, 0.57067451, 0.66593472, 0.34228504,
       0.60393603, 0.84631651, 0.68722534, 0.91076925, 0.28703303,
       0.54869174, 0.00763579])