In [9]:
import numpy as np

In [ ]:
What is pandas?
Data structures in pandas
What is numpy array
Difference between array and list
Difference between series and dataframe
Can we join multiple arrays
Create a dataframe using array
Transpose
Random.randint         done



**Pandas** is an open-source library that is made mainly for working with relational 
or labeled data both easily and intuitively. It provides various data structures and operations for manipulating
**numerical data and time series**. This library is built on top of the NumPy library.
Pandas is fast and it has high performance & productivity for users.

series , data frame , panel

**series**is a one-dimensional labeled array and capable of holding data of any type (integer, string, float, python objects, etc.)

**data frame**Pandas DataFrame is a two-dimensional size-mutable, potentially heterogeneous tabular data structure with labeled axes (rows and columns). A Data frame is a two-dimensional data structure, i.e., data is aligned in a tabular fashion in rows and columns like a spreadsheet or SQL table, or a dict of Series objects. . **Pandas DataFrame consists of three principal components, the data, rows, and columns.

Creating a Pandas DataFrame
In the real world, a Pandas DataFrame will be created by loading the

![aee1ae10-2d57-456a-833b-c09aced5f3e3.jpg](attachment:aee1ae10-2d57-456a-833b-c09aced5f3e3.jpg)

**NumPy** is a library for the Python programming language, 
adding support for large, multi-dimensional arrays and matrices, 
along with a large collection of high-level mathematical functions to operate on these arrays

S.No.	List	Array
1	List is used to collect items that usually consist of elements of multiple data types.
    An array is also a vital component that collects several items of the same data type.

2	List cannot manage arithmetic operations.
Array can manage arithmetic operations.

3	It consists of elements that belong to the different data types.
    It consists of elements that belong to the same data type.

4	When it comes to flexibility, the list is perfect as it allows easy modification of data.
    When it comes to flexibility, the array is not suitable as it does not allow easy modification of data.

5	It consumes a larger memory.
    It consumes less memory than a list.

6	In a list, the complete list can be accessed without any specific looping.
In an array, a loop is mandatory to access the components of the array.

7	It favors a shorter sequence of data.
    It favors a longer sequence of data.

In [ ]:
sin >> Opp/Hyp
cos = Adj/Hyp
sec= 1/cos
cot = 1/tan > cos/sin
tan = sin/cos
cosec = Hyp/Opp >> 1/sin

## radian to degree

In [2]:
np.pi  # radian >> 180 degree
# sin(30) >>1/2 =0.5

3.141592653589793

In [ ]:
np.pi >> it return pi value in radian

In [3]:
np.rad2deg(np.pi)  # rad to degree

180.0

In [3]:
np.sin(np.pi/6)  #180/6 =30       

0.49999999999999994

In [5]:
np.cos(np.pi/4) # 45

0.7071067811865476

In [8]:
round(np.cos(np.pi/2)) # 90

0

## degree to radian

In [5]:
arr = np.array([0,30,45,60,90])# degree
ar1_rad = np.deg2rad(arr)
ar1_rad

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [10]:
# radian to degree
arr2 = np.array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])
degree = np.rad2deg(arr2)
degree

array([ 0.        , 30.00000025, 44.99999981, 59.99999993, 90.00000018])

## linear

In [ ]:
2x + 4y = 20 >>>>> eq 1 *3
3x + 5y = 15 >>>>>>eq 2 *2
x & y
6x + 12y = 60
6x + 10y = 30
y  > 15 ans
x > -20 ans

In [12]:
# 2.8x + 4y = 20 
# 3x + 5y = 15
[[2.8,4],[3.85,5]]
[20,15]

[20, 15]

In [13]:
A = np.array([[2.8,4],[3.8,5]])
B = np.array([20,15])
result = np.linalg.solve(A,B)
result

array([-33.33333333,  28.33333333])

## interview Question

## inverse of matrix

In [12]:
arrA = np.array([[2,5],[3,4]])
arrA

array([[2, 5],
       [3, 4]])

In [13]:
np.linalg.inv(arrA)

array([[-0.57142857,  0.71428571],
       [ 0.42857143, -0.28571429]])

## index

In [16]:
list1 = [3,4,5,6,5,7,5,6,5]
list1.index(5)

2

In [17]:
arr = np.array(list1)
np.where(arr == 5)

(array([2, 4, 6, 8], dtype=int64),)

## sqrt

In [16]:
lst1 = [25,64,100,4]
import math
math.sqrt(25)

5.0

In [20]:
math.sqrt(lst1)

TypeError: must be real number, not list

In [22]:
arr1 = np.array(lst1)
np.sqrt(arr1)

array([ 5.,  8., 10.,  2.])

## cube root

In [24]:
arr1 = np.array([8,27,125,64])
np.cbrt(arr1)

array([2., 3., 5., 4.])

In [18]:
arr = np.ones(10,int)
arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
[5,5,5,5,5,5]

In [29]:
arr = np.ones(10,int)
arr*5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [27]:
arr = np.ones(10,int)
arr+4

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [19]:
arr = np.full(10,7)  # shape & filled value
arr


array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

## copy()

In [32]:
arr = np.full(10,5)  # shape & filled value
arr[1] = 100
arr

array([  5, 100,   5,   5,   5,   5,   5,   5,   5,   5])

In [34]:
arr = np.full(10,5)  # shape & filled value
arr1 = arr
arr[1] = 100
print(arr)
print(arr1)

[  5 100   5   5   5   5   5   5   5   5]
[  5 100   5   5   5   5   5   5   5   5]


In [35]:
arr = np.full(10,5)  # shape & filled value
arr1 = arr.copy() # deep copy
arr[1] = 100
print(arr)
print(arr1)

[  5 100   5   5   5   5   5   5   5   5]
[5 5 5 5 5 5 5 5 5 5]


In [36]:
arr = np.array([[3,4],[4,5]])
arr

array([[3, 4],
       [4, 5]])

In [38]:
arr[1,0] = 100

In [39]:
arr

array([[  3,   4],
       [100,   5]])

In [40]:
arr = np.array([[3,4],[4,5]])
arr1 = arr
arr[1,0] = 100
print(arr)
print(arr1)

[[  3   4]
 [100   5]]
[[  3   4]
 [100   5]]


In [41]:
arr = np.array([[3,4],[4,5]])
arr1 = arr.copy()
arr[1,0] = 100
print(arr)
print(arr1)

[[  3   4]
 [100   5]]
[[3 4]
 [4 5]]


## Traspose

In [26]:
arr = np.array([[3,41],[4,5]])
print(arr)
arr.T  # Transpose

[[ 3 41]
 [ 4  5]]


array([[ 3,  4],
       [41,  5]])

## size

In [10]:
import numpy as np 
arr = np.array([[3,41],[4,5]])
# np.shape(arr)
np.shape(arr)
# array1=np.shape(arr)
# print(array1)
# arr.size

(2, 2)

In [27]:
arr = np.array([3,41,4,5])
arr.size

4

In [48]:
arr = np.array([3,41,4,5])

In [49]:
len(arr)

4

## To know index of max & min element

In [8]:
arr = np.array([66,55,17,88,19,2,3,4])
N1=np.where(arr==arr.max())
N1[0].tolist()
N1

(array([3], dtype=int64),)

In [16]:
arr = np.array([66,55,17,88,19,2,3,4])
# arr.argmax()
# arr.argmin()
# arr.argsort()
print(f"The maximun value is={arr.max()} at index={arr.argmax()}")

The maximun value is=88 at index=3


In [57]:
arr = np.array([66,55,17,88,19,2,3,4])
arr.argmin()

5

## Sort index wise

In [58]:
arr = np.array([66,55,17,88,19,2,3,4])
arr.argsort()

array([5, 6, 7, 2, 4, 1, 0, 3], dtype=int64)

## np.tile

In [44]:
# [1,2,3,4]  # o/p >> [1,2,3,4,1,2,3,4]
l =  [1,2,3,4] 
l*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [64]:
arr1 = np.array(l)
arr2 = np.array(l)
np.concatenate([arr1,arr2])

array([1, 2, 3, 4, 1, 2, 3, 4])

In [ ]:
np.concatenate(arr1,arr1)
Aditi Shalu21:08
lst1 = [1,2,3,4]
lst1.extend(lst1)
lst1
sagar Sonawane21:08
arr1*2
AMAR SHRINATH21:09
np.append(arr1, arr1)

In [ ]:
np.append(arr1, arr1)

In [65]:
np.tile(l,2)

array([1, 2, 3, 4, 1, 2, 3, 4])

## repeat

In [ ]:
l = [1,2,3,4] >>o/p [1,1,2,2,3,3,4,4]

In [67]:
np.sort(np.tile(l,2))

array([1, 1, 2, 2, 3, 3, 4, 4])

In [68]:
np.repeat(l,2)

array([1, 1, 2, 2, 3, 3, 4, 4])